### ISSUE TITLE
Remove ztm-builder

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/ztm#117]
Seem like we don't need it due to Jenkins already start container with `-u`.

**Comment by thebevrishot** [comment]
Building process need home directory then we still need to create a user and its directory.

**Comment by ultimaweapon** [comment]
GitHub Actions don't need this anymore so we can remove it.

**Comment by thebevrishot** [comment]
solved by https://github.com/zcoinofficial/ztm/pull/139
