### ISSUE TITLE
Tesging on CI is not stable

### ISSUE THREAD

**Issue by thebevrishot** [zcoinofficial/ztm#32]
Many time CI failed on testing phase and then success after try to rebuild many times.
But on my machine it rarely fails.

You can check log message here https://ci.zcoin.io/job/ztm/job/main/job/PR-28/

- [x] Implementation [0.5]
- [x] Review [0.5]

**Comment by ultimaweapon** [comment]
What I guess is `zcoind` crashed somehow. My idea is we should wait for new release that come with Exodus enhancement and try that binary instead.

**Comment by ultimaweapon** [comment]
After upgraded the problems not solved.

**Comment by ultimaweapon** [comment]
Fixed by #131.
